### ISSUE TITLE
Use _select on remove()

### ISSUE THREAD

**Issue by Straightline** [bwgjoseph/feathers-ottoman#2]
Should `allData` be run through the `_select` function on remove?
https://github.com/bwgjoseph/feathers-ottoman/blob/14565408169d4bd8b24249113198908713093980/src/index.ts#L376

**Comment by DaddyWarbucks** [comment]
^^ Thats me BTW...didn't realize I was signed in to a different account.

**Comment by bwgjoseph** [comment]
It's not necessary because `_find` would already have the correct data set based on the `$select` passed in as the query

https://github.com/bwgjoseph/feathers-ottoman/blob/14565408169d4bd8b24249113198908713093980/src/index.ts#L373

With that said, I went back to check on the other methods for multi-operation might not need to run `_select` as well that uses `_find` beforehand

Will run a few more test to verify
